### ISSUE TITLE
EnableInfoCache shows server as not VAC enabled

### ISSUE THREAD

**Issue by G-Force007** [danielga/gmsv_serversecure#41] opened 2019-11-22 17:21 UTC
Latest version with serversecure.EnableInfoCache(true) displays our server as VAC disabled.
Windows Server 2016
Version: 1.5.28

**Comment by danielga** [comment] 2019-11-22 17:23
Did you request info from the server multiple times, during an extended period of time? It might take a few seconds to update the VAC status.

**Comment by G-Force007** [comment] 2019-11-22 17:25
Yep, server has been running multiple hours.
Manually executed: serversecure.RefreshInfoCache() which did not help.

It immediately shows VAC as disabled once I run serversecure.EnableInfoCache(true) and fixes itself once I disable it.

**Comment by G-Force007** [comment] 2019-11-22 17:28
Note that the map has restarted since the servers been running.

**Comment by danielga** [comment] 2019-11-22 17:28
Hmm, what if you launch the server cold, is the status correct?

**Comment by G-Force007** [comment] 2019-11-22 17:32
Launching the server with serversecure.EnableInfoCache(true) still displays VAC disabled. Seems the pointer may be null?

**Comment by danielga** [comment] 2019-11-22 17:34
Shouldn't be, unless it's failing all the time, since I made the code retry every time (when we don't have the pointers) the cache is refreshed, either automatically or manually.

**Comment by G-Force007** [comment] 2019-11-22 17:39
<img width="1052" alt="Screen Shot 2019-11-23 at 4 38 32 am" src="https://user-images.githubusercontent.com/2627970/69447720-3819b900-0dab-11ea-96b4-d65cb16d35f4.png">
<img width="908" alt="Screen Shot 2019-11-23 at 4 38 56 am" src="https://user-images.githubusercontent.com/2627970/69447723-3b14a980-0dab-11ea-9ef4-d5b25d9a060b.png">

**Comment by danielga** [comment] 2019-11-22 18:04
I hope I don't have to use the old method of getting Steam API interfaces, it was hacky as hell. I'm currently using the steam_api binaries basically directly, querying for the necessary interfaces that give me VAC status. I don't know what could be going wrong there, besides possible interface versions conflicts.

**Comment by danielga** [comment] 2019-11-23 18:43
I'm unable to reproduce this on Garry's Mod main branch, Windows 10, with the module downloaded from the 1.5.28 release tag. Can you write down your serversecure config?

**Comment by danielga** [comment] 2019-11-23 19:16
I have also tried on Ubuntu 18.04.2 LTS, unable to reproduce.

**Comment by FarukGamer** [comment] 2019-11-26 01:22
fortunately, this bug appears on my server aswell, I had to revert back to a older version. 

I am running on Debian 10.2 with Kernel version 5.3.12 and the module is v1.5.28

Atm I don't have a console log ready to upload, but will reply soon again.

**Comment by danielga** [comment] 2019-11-26 23:29
After looking at the Steam API headers and matching interface versions with Garry's Mod, I thought that the steam_api binary could be using whatever Steam instance is currently active, allowing the interface versions defined in my module (that are higher than Garry's Mod) to work. I've made some changes on sourcesdk-minimal and [releasing 1.5.29](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.29).

**Comment by G-Force007** [comment] 2019-11-27 20:05
It is now fixed for me @danielga

**Comment by danielga** [comment] 2019-11-27 21:12
Fixed the tag. [My Steam profile](http://steamcommunity.com/profiles/76561197999418456). Closing the issue since it's fixed.

**Closed by danielga** 2019-11-27 21:12 UTC
Labels: bug
