### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by AMD-NICK** [danielga/gmsv_serversecure#2] opened 2015-10-14 10:12 UTC
When I use this module my server crashes after 5-10 minutes worktime.
Also if it's important the server will be crash only if it have 2+ players online.

### debug.log: ###
```
CRASH: Wed Oct 14 12:18:33 MSK 2015
Start Line: ./srcds_linux -console -game garrysmod -condebug +exec server.cfg -tickrate 32 -port 28082 -authkey D11BEE3E7A21**************700C69 +host_workshop_collection 462***075 +hunkalloclightmaps 0 +maxplayers 50 +map rp_evocity2_v2p -debug
[New LWP 29153]
[New LWP 29154]
[New LWP 29159]
[New LWP 29260]
[New LWP 29259]
[New LWP 29271]
[New LWP 29171]
[New LWP 29155]
[New LWP 29158]
[New LWP 29164]
[New LWP 29175]
[New LWP 29156]
[New LWP 29157]
[New LWP 29173]
#0  0xf750600c in ?? ()
End of Source crash report
```

I use this version of the module: https://github.com/danielga/gmsv_serversecure/releases/tag/1.2.1
My OS is *Ubuntu Server 12.04*

**Comment by danielga** [comment] 2015-10-14 12:56
Which features were you using? Threaded socket reading, A2S_INFO response cache, file validation, query rate limiting, etc. Try to be as specific as possible. Config values for the module might help as well.
If you use the example.lua file without any content changes, do tell.

**Comment by AMD-NICK** [comment] 2015-10-14 13:08
yeah, I'm using example.lua file. I just create file /addons/utils/lua/autorun/server/gmsv_serversecure.lua and paste example.lua content to him

**Comment by danielga** [comment] 2015-10-14 19:24
Try commenting the lines related to info response cache (serversecure.EnableInfoCache and serversecure.SetInfoCacheTime, just add -- before them). See if that stops the crashes. If it does, it'll narrow down the problem to cache updating.

**Comment by AMD-NICK** [comment] 2015-10-14 19:28
> Try commenting the lines related to info response cache

But it feature is most important for me

**Comment by AMD-NICK** [comment] 2015-10-14 19:29
I have comment all  lines excepting A2S_INFO response cache. 
Will tell about result

**Comment by AMD-NICK** [comment] 2015-10-16 00:30
So. I comment all lines excepting A2S_INFO response cache and server wasn't crash yesterday

**Comment by danielga** [comment] 2015-10-16 16:57
Someone previously used the module and told me by disabling A2S_INFO response cache it stopped crashing. So this leads me to believe it is a combination of features that leads to a crash.

**Comment by fruitwasp** [comment] 2015-11-16 15:44
It kept crashing on my server too, in which I commented out the file validation line, because it crashed just after bunch of ```[ServerSecure] Checking file "user_custom\12\122345a.dat``` prints

**Comment by fruitwasp** [comment] 2015-11-16 16:34
Seems to stop the crashes just after the 2nd player joined, now it crashes on random times

**Comment by uRandomAlex** [comment] 2016-04-22 05:04
This module even not compiling (according to README), sadly ;(
I don't know many C's, but this will be great if you will fix this module. I think that you've already fixed ServerSecure and running it on some server, then it will be simple to copy some code from your private version.

**Comment by danielga** [comment] 2016-04-25 00:11
@uRandomAlex [version 1.3.3 released](https://github.com/danielga/gmsv_serversecure/releases/tag/1.3.3)

**Comment by uRandomAlex** [comment] 2016-04-25 05:58
@danielga Thanks! Testing it now!

**Comment by uRandomAlex** [comment] 2016-04-26 11:06
"Unable to load module library serversecure" (or something like this). It's also preventing some Lua-code from run, i.e. fretta's round system don't work.

**Comment by uRandomAlex** [comment] 2016-06-01 10:29
Crashes are gone. Sometimes join time on my server is very long, but I think that the problem is in settings. I've tweaked them a bit now, let's see what happens.

**Comment by uRandomAlex** [comment] 2016-06-10 13:22
Settings don't matter - this module improves client loading times a lot, so they just timeout-kicked! Is there any solution for this problem?

**Comment by danielga** [comment] 2016-06-10 15:39
I'm going to need the settings you're using to attempt a reproduction.

**Comment by uRandomAlex** [comment] 2016-06-10 15:49
@danielga 
```
hook.Add("Initialize", "serversecure initialization", function()
	require( "serversecure" )

	--serversecure.EnableFirewallWhitelist( bool ) -- enable "firewall" whitelist, any client not in the whitelist doesn't see the server
	--serversecure.AddWhitelistIP( ip_in_integer_format ) -- add an IP to the whitelist
	--serversecure.RemoveWhitelistIP( ip_in_integer_format ) -- remove an IP from the whitelist
	--serversecure.ResetWhitelist() -- reset the whitelist

	--serversecure.EnableFirewallBlacklist( boolean ) -- enable "firewall" blacklist, any client in the blacklist doesn't see the server
	--serversecure.AddBlacklistIP( ip_in_integer_format ) -- add an IP to the blacklist
	--serversecure.RemoveBlacklistIP( ip_in_integer_format ) -- remove an IP from the blacklist
	--serversecure.ResetBlacklist() -- reset the blacklist

	serversecure.EnableFileValidation( false ) -- validates files requested by clients for download

	//serversecure.EnableThreadedSocket( true ) -- receives packets from the game socket on another thread (as well as analyzing it)

	serversecure.EnablePacketValidation( true ) -- validates packets for having correct types, size, content, etc.

	serversecure.EnableInfoCache( true ) -- enable A2S_INFO response cache
	serversecure.SetInfoCacheTime( 5 ) -- seconds for cache to live (default is 5 seconds)

	serversecure.EnableQueryLimiter( true ) -- enable query limiter (similar to Source's one but all handled on the same place)
	serversecure.SetMaxQueriesWindow( 60 ) -- timespan over which to average query counts from IPs (default is 30 seconds)
	serversecure.SetMaxQueriesPerSecond( 1 ) -- maximum queries per second from a single IP (default is 1 per second)
	serversecure.SetGlobalMaxQueriesPerSecond( 50 ) -- maximum total queries per second (default is 60 per second)
	print( "[sv_serversecure.lua] Done!" )
end)
```

**Comment by uRandomAlex** [comment] 2016-08-25 00:34
This issue was fixed. @danielga can close it.

**Closed** 2016-08-25 00:39 UTC
Labels: bug
