### ISSUE TITLE
Server crashes when serversecure.RefreshInfoCache()

### ISSUE THREAD

**Issue by cannon** [danielga/gmsv_serversecure#13] opened 2017-04-22 18:37 UTC
I'm using the latest gmod version and latest version of this addon.

```	
print("Loading serversecure")
	require("serversecure")
	if serversecure.EnableInfoCache==nil then
		serversecure.PostInitialize()
	end

	serversecure.EnableInfoCache(true)
	serversecure.SetInfoCacheTime(2)

	serversecure.EnableThreadedSocket(true)

	timer.Create("ServerSecureInfoCache", 5, 0, function()
		serversecure.RefreshInfoCache()
	end)
```

**Comment by danielga** [comment] 2017-04-25 19:45
Bug confirmed, caused by the following piece of code in `BuildReplyInfo`, lines 306-307.

```cpp
ISteamGameServer *steamGS = gameserver_context != nullptr ? gameserver_context->m_pSteamGameServer : nullptr;
info_cache_packet.WriteByte( steamGS != nullptr ? steamGS->BSecure( ) : false );
```

**Comment by danielga** [comment] 2017-05-02 21:39
I believe this is fixed by the [latest commit](https://github.com/danielga/gmsv_serversecure/commit/626fd713d593a6e16f2c84d047fe3f996a989f2d).

**Closed by danielga** 2017-05-02 21:39 UTC
Labels: bug
